Use serde to load config
SUPERAndroidAnalyzer/super pull request #120
Opened 2017-04-18 23:22 UTC by gnieto

Use serde to load config files to make easier the config parsing. 
Should close: https://github.com/SUPERAndroidAnalyzer/super/issues/117

2017-04-19 19:06 UTC, gnieto commented on config.toml.sample
> +[unknown_permissions]
This is the unique way I've found to be able to load the unknown permissions, but this can break previous configs!

2017-06-02 07:27 UTC, Razican reviewed
Can this be upgraded to serde 1.0.x? Looks good for the rest, with the couple of comments I made :) thanks!

2017-06-02 07:27 UTC, Razican commented on src/utils.rs
> +/// Prints a warning to `stderr` in yellow.
Isn't a config error a fatal error (instead of a warning)?

2017-06-02 07:27 UTC, Razican commented on config.toml.sample
> +[unknown_permissions]
Yes, makes sense, nevertheless, `name` should be removed, since it's always going to be *unknown*.

2017-06-03 12:41 UTC, gnieto commented on src/utils.rs
> +/// Prints a warning to `stderr` in yellow.
On develop, when one of the fields of the config files where not properly filled, it raised a warning, but kept the well formed values.

With the current code, Serde stops deserializing when some field is incorrect and returns an Error. This method is to print this error that serde is returning. Now, in this case, we are ignoring ALL the configuration loaded from the malformed file and keeps loading the configuration from other sources (CLI, for example).

If you want, I can bubble up the serde error if there is some malformed value and we can remove this method.

2017-06-03 15:35 UTC, Razican commented on src/utils.rs
> +/// Prints a warning to `stderr` in yellow.
I would bubble up, yes, if the configuration has an issue, we should tell that and stop the loading.

2017-06-03 18:53 UTC, gnieto commented
Pushed one more commit changing the config loading.
As we are using serde_derive, it's not possible to mimic the previous behaviour: Load from /etc/config.toml, then decorate the config with the config.toml on the root and finally the CLI flags.

Now, it will try to load from /etc/config.toml if ran on Unix and config.toml non existing on the current path. On other platforms, `config.toml` is loaded if it exsits.
If non of them exists, the default values are used.

Are you ok with the new behaviour?

2017-06-03 18:58 UTC, Razican commented
I like the workflow, yes, but wasn't that the behaviour before?

2017-06-03 18:58 UTC, Razican requested changes
Looks good for me, just that small detail (it's not a new bug, but it would be great if you could fix it)

2017-06-03 18:58 UTC, Razican commented on src/main.rs
> +    let global_config_path = PathBuf::from("/etc/config.toml");
Actually, this was a bug before, it should be `/etc/super-analyzer/config.toml`.

2017-06-03 21:13 UTC, gnieto commented on src/main.rs
> +    let global_config_path = PathBuf::from("/etc/config.toml");
Changed!

2017-06-04 12:21 UTC, Razican approved these changes
Looks good!

2017-06-21 07:52 UTC, merged