Support config options via command line
SUPERAndroidAnalyzer/super pull request #76
Opened 2016-10-23 22:29 UTC by b52

This is going to be a fix for #49.

Though, it's still not clear to me what is meant by "disabling permissions". Could you elaborate what to do exactly?

2016-10-25 09:06 UTC, Razican commented
Permissions would be to disable permission checks, one by one, but we are still not sure if we would like to include labels or some sort of identifiers. So, for now, no permision check modifications through CLI :)

2016-10-25 09:17 UTC, Razican requested changes
Check the changes I proposed. Could you also add some documentation to setters?

Thanks for the pull request, in any case, looks great!

2016-10-25 09:17 UTC, Razican commented on src/main.rs
> +        config.set_threads(threads.parse().expect("An integer"));
This actually should be an integer smaller than `u8::MAX`.

2016-10-25 09:17 UTC, Razican commented on src/main.rs
> +            .long("rules-json")
As said above, no short option, and a `--rules` option would be enough.

2016-10-25 09:17 UTC, Razican commented on src/main.rs
> +        .arg(Arg::with_name("disable-permissions")
As I said in the comment, I think is better to remove permissions for now.

2016-10-25 09:17 UTC, Razican commented on src/main.rs
> +        .arg(Arg::with_name("downloads-folder")
Here `--downloads` should be enough., and I would not add the short option.

2016-10-25 09:17 UTC, Razican commented on src/main.rs
> +            .short("D")
Same as before `--dist` should be enough, and without the short option.

2016-10-25 09:17 UTC, Razican commented on src/main.rs
> +            .help("Distribution folder.")
Maybe a description such as *"Folder where distribution files will be extracted"* would be better.

2016-10-25 09:17 UTC, Razican commented on src/main.rs
> +            .long("results-folder")
Same as above, no short option and only `--results` instead of `--results-folder`.

2016-10-25 09:17 UTC, Razican commented on src/main.rs
> +            .long("apktool-file")
Same as above, without the short option and only `--apktool`.

2016-10-25 09:17 UTC, Razican commented on src/main.rs
> +            .long("dex2jar-folder")
Same as above, no short option and `--dex2jar` only.

2016-10-25 09:17 UTC, Razican commented on src/main.rs
> +            .long("jd-cmd-file")
As before, no short option and `--jd-cmd` only.

2016-10-25 09:17 UTC, Razican commented on src/main.rs
> +            .short("T")
This will be changed with the new templating system, but as before, no short option and `--template` as the option.

2016-10-27 20:14 UTC, b52 commented on src/main.rs
> +        config.set_threads(threads.parse().expect("An integer"));
`parse()` ensures this, however in a not very userfriendly way. How should I instead do this?

2016-10-27 20:39 UTC, b52 commented
@Razican Done.

2016-10-27 20:43 UTC, Razican approved these changes

2016-10-27 20:46 UTC, Razican commented
Looks great! I'll merge as soon as tests pass, thanks!

2016-10-27 22:02 UTC, merged